# @file
# Travis CI integration.

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache/files

language: php

php:
  - 7.2
  - 7.3

env:
  global:
    # Ensure composer is able to apply patches.
    - COMPOSER_EXIT_ON_PATCH_FAILURE=1
    # DRUPAL_TI Testing.
    - SIMPLETEST_DB="mysql://root:@localhost/drupal_travis_db"
    - SIMPLETEST_BASE_URL="http://localhost:8888"
    # Ignore deprecation warnings.
    - SYMFONY_DEPRECATIONS_HELPER=weak

  matrix:
    # Latest stable release
    - DRUPAL_CORE="~8.8"
    # Latest current dev branch
    - DRUPAL_CORE="^8.8"
    # Latest future dev branch
    - DRUPAL_CORE="^8"

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
      env: DRUPAL_CORE="^8"
    - php: 7.3
      env: DRUPAL_CORE="^8"
    - php: 7.3
      env: DRUPAL_CORE="^8.8"
    - php: 7.3
      env: DRUPAL_CORE="~8.8"

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  # Remove xdebug. We aren't generating code coverage, and it slows down Composer.
  - phpenv config-rm xdebug.ini || true
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - phpenv config-add $TRAVIS_BUILD_DIR/travis-ci/travis.php.ini
  # Track our general build directory.
  - export DRUPAL_BUILD_ROOT="$(dirname "$TRAVIS_BUILD_DIR")"
  - export VENDOR_DIR="$(dirname "$TRAVIS_BUILD_DIR")/drupal/vendor"

install:
  - ./travis-ci/install.sh

before_script:
  - $DRUPAL_BUILD_ROOT/drupal/vendor/bin/phpcs --config-set installed_paths $VENDOR_DIR/drupal/coder/coder_sniffer,$VENDOR_DIR/wimg/php-compatibility
  - php -S localhost:8888 -t $DRUPAL_BUILD_ROOT/drupal/web &
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS drupal_travis_db"

script:
  - $VENDOR_DIR/bin/parallel-lint $TRAVIS_BUILD_DIR
  - $VENDOR_DIR/bin/phpcs $TRAVIS_BUILD_DIR --standard=$TRAVIS_BUILD_DIR/phpcs.xml
  # @todo: Add ESLint
  - $VENDOR_DIR/bin/phpunit -c $DRUPAL_BUILD_ROOT/drupal/web/core/phpunit.xml.dist --group=gdpr

notifications:
  email: false
  irc: "chat.freenode.net#drupal-gdpr"
